#ifndef FIBERS_CONSTANTS_KERNEL_
#define FIBERS_CONSTANTS_KERNEL_

#include "../common.h"

#define BENCHMARK
#define FORCE_3D
#define MAGMA

#define DIMENSIONS (3)
#define NUMBER_OF_FIBERS (32)
#define TIMESTEP (0.1)
#define NUMBER_OF_TIMESTEPS (10)
#define SLENDERNESS (0.01f)
#define NUMBER_OF_TERMS_IN_FORCE_EXPANSION (5)
#define NUMBER_OF_QUADRATURE_POINTS_PER_INTERVAL (3)
#define NUMBER_OF_QUADRATURE_INTERVALS (8)
#define TOTAL_NUMBER_OF_QUADRATURE_POINTS (NUMBER_OF_QUADRATURE_POINTS_PER_INTERVAL * NUMBER_OF_QUADRATURE_INTERVALS)

#define TOTAL_NUMBER_OF_ROWS (NUMBER_OF_FIBERS * NUMBER_OF_TERMS_IN_FORCE_EXPANSION * DIMENSIONS)

__constant__ float quadrature_points[TOTAL_NUMBER_OF_QUADRATURE_POINTS];
__constant__ float quadrature_weights[TOTAL_NUMBER_OF_QUADRATURE_POINTS];
__constant__ float legendre_polynomials[TOTAL_NUMBER_OF_QUADRATURE_POINTS * NUMBER_OF_TERMS_IN_FORCE_EXPANSION];
__constant__ float lambda[NUMBER_OF_TERMS_IN_FORCE_EXPANSION];
__constant__ float eigen[NUMBER_OF_TERMS_IN_FORCE_EXPANSION];

#endif //FIBERS_CONSTANTS_KERNEL_

